### ISSUE TITLE
Couldn't connect to 127.0.0.1 port 2222

### ISSUE THREAD

**Issue by karthikeayan** [jianzhongli/RemoteTerminal#1]
![image](https://cloud.githubusercontent.com/assets/5030782/25986444/9dacff92-370d-11e7-9a66-fdba72bf49a4.png)

I couldn't connect to my Ubuntu VM running on VirtualBox. SSH fine in other terminal applications.

**Comment by jianzhongli** [comment]
> As for the limitation that Windows Store Apps cannot connect to localhost: that is correct, this is (by default) explicitly forbidden.

See this [issue](https://github.com/spodskubka/RemoteTerminal/issues/6).
